// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srlxecametekeahhhrrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybHhlY2FtZXRla2VhaGhocnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODkzNzcsImV4cCI6MjA2OTU2NTM3N30.0FIzWdVxD8LVK_ol3Kn_z9b8aVEec2hQri9-zluJbQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});